//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaYetex.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo_Producto
    {
        public long Id_Costo_Producto { get; set; }
        public int Id_Producto { get; set; }
        public decimal CostoxUnidad { get; set; }
        public System.DateTime Fecha_Inicial { get; set; }
        public Nullable<System.DateTime> Fecha_Final { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
