//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaYetex.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public long Id_Detalle_Pedido { get; set; }
        public long Orden_Pedido { get; set; }
        public int Id_Producto { get; set; }
        public short Id_Color { get; set; }
        public int Cantidad { get; set; }
        public int Id_Logotipo { get; set; }
        public string Observaciones { get; set; }
        public decimal Valor_Venta_Unitario { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Logotipo Logotipo { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
