//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaYetex.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Costo_Producto = new HashSet<Costo_Producto>();
            this.Detalle_Pedido = new HashSet<Detalle_Pedido>();
        }
    
        public int Id_Producto { get; set; }
        public int Id_Prenda { get; set; }
        public int Id_Tipo_Prenda { get; set; }
        public string Talla { get; set; }
        public decimal CostoxUnidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Costo_Producto> Costo_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual Prenda Prenda { get; set; }
        public virtual Tipo_Prenda Tipo_Prenda { get; set; }
    }
}
